[tools]
trufflehog = "latest"
uv = "latest"
pre-commit = "latest"
taplo = "latest"
ruff = "latest"
yq = "latest"
"pipx:yamlfix" = "latest"
yamllint = "latest"
"pipx:ty" = "latest"

[settings]
experimental = true
lockfile = true
#locked = true
