indent-width = 4
line-length = 88
target-version = "py313"

[lint]
  dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
  fixable = ["ALL"]
  ignore = ["D100", "D105", "D107", "D212", "D413", "SIM117"]
  select = ["ALL"]
  unfixable = []

  [lint.isort]
    combine-as-imports = true

  [lint.per-file-ignores]
    "test_app.py" = ["INP001", "S101"]

[format]
  docstring-code-format = false
  docstring-code-line-length = "dynamic"
  indent-style = "space"
  line-ending = "lf"
  quote-style = "double"
  skip-magic-trailing-comma = false
