name: Version
on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      - uv.lock
      - Dockerfile
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
permissions: read-all
jobs:
  version:
    name: Versioning
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    permissions:
      contents: write
    environment:
      name: versioning
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v7.0.0
        with:
          enable-cache: true
          activate-environment: true
      - name: Increase the patch version
        run: uv version --bump patch
      - name: Get Package version from pyproject.toml
        id: get_package_version
        uses: mikefarah/yq@v4.49.1
        with:
          cmd: yq -roy '.project.version' pyproject.toml
      - name: Commit updated count
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: 'Tag: ${{ steps.get_package_version.outputs.result }}'
          tagging_message: ${{ steps.get_package_version.outputs.result }}
