name: Version
on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      - uv.lock
      - Dockerfile
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false
permissions: read-all
jobs:
  version:
    name: Versioning
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'mergify[bot]'
    permissions:
      contents: write
    environment:
      name: versioning
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          enable-cache: true
          activate-environment: true
      - name: Increase the patch version
        run: uv version --bump patch
      - name: Get Package version from pyproject.toml
        id: get_package_version
        uses: mikefarah/yq@5a7e72a743649b1b3a47d1a1d8214f3453173c51 # v4.52.4
        with:
          cmd: yq -roy '.project.version' pyproject.toml
      - name: Commit updated count
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'Tag: ${{ steps.get_package_version.outputs.result }}'
          tagging_message: ${{ steps.get_package_version.outputs.result }}
